// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package order

import (
	"context"
	"fmt"
	"user_system/kitex_gen/GoStudyWork/userSystem/user"
)

type OrderService interface {
	GetUserInfo(ctx context.Context, userid int64) (r *user.UserInfo, err error)
}

type OrderServiceGetUserInfoArgs struct {
	Userid int64 `thrift:"userid,1" frugal:"1,default,i64" json:"userid"`
}

func NewOrderServiceGetUserInfoArgs() *OrderServiceGetUserInfoArgs {
	return &OrderServiceGetUserInfoArgs{}
}

func (p *OrderServiceGetUserInfoArgs) InitDefault() {
}

func (p *OrderServiceGetUserInfoArgs) GetUserid() (v int64) {
	return p.Userid
}
func (p *OrderServiceGetUserInfoArgs) SetUserid(val int64) {
	p.Userid = val
}

func (p *OrderServiceGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetUserInfoArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceGetUserInfoArgs = map[int16]string{
	1: "userid",
}

type OrderServiceGetUserInfoResult struct {
	Success *user.UserInfo `thrift:"success,0,optional" frugal:"0,optional,user.UserInfo" json:"success,omitempty"`
}

func NewOrderServiceGetUserInfoResult() *OrderServiceGetUserInfoResult {
	return &OrderServiceGetUserInfoResult{}
}

func (p *OrderServiceGetUserInfoResult) InitDefault() {
}

var OrderServiceGetUserInfoResult_Success_DEFAULT *user.UserInfo

func (p *OrderServiceGetUserInfoResult) GetSuccess() (v *user.UserInfo) {
	if !p.IsSetSuccess() {
		return OrderServiceGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*user.UserInfo)
}

func (p *OrderServiceGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetUserInfoResult(%+v)", *p)
}

var fieldIDToName_OrderServiceGetUserInfoResult = map[int16]string{
	0: "success",
}
