// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
)

type UserID struct {
	No int64 `thrift:"no,1" frugal:"1,default,i64" json:"no"`
}

func NewUserID() *UserID {
	return &UserID{}
}

func (p *UserID) InitDefault() {
}

func (p *UserID) GetNo() (v int64) {
	return p.No
}
func (p *UserID) SetNo(val int64) {
	p.No = val
}

func (p *UserID) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserID(%+v)", *p)
}

var fieldIDToName_UserID = map[int16]string{
	1: "no",
}

type UserInfo struct {
	Id   *UserID `thrift:"id,1" frugal:"1,default,UserID" json:"id"`
	Name string  `thrift:"name,2" frugal:"2,default,string" json:"name"`
}

func NewUserInfo() *UserInfo {
	return &UserInfo{}
}

func (p *UserInfo) InitDefault() {
}

var UserInfo_Id_DEFAULT *UserID

func (p *UserInfo) GetId() (v *UserID) {
	if !p.IsSetId() {
		return UserInfo_Id_DEFAULT
	}
	return p.Id
}

func (p *UserInfo) GetName() (v string) {
	return p.Name
}
func (p *UserInfo) SetId(val *UserID) {
	p.Id = val
}
func (p *UserInfo) SetName(val string) {
	p.Name = val
}

func (p *UserInfo) IsSetId() bool {
	return p.Id != nil
}

func (p *UserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfo(%+v)", *p)
}

var fieldIDToName_UserInfo = map[int16]string{
	1: "id",
	2: "name",
}

type UserService interface {
	GetUserInfo(ctx context.Context, userid *UserID) (r *UserInfo, err error)
}

type UserServiceGetUserInfoArgs struct {
	Userid *UserID `thrift:"userid,1" frugal:"1,default,UserID" json:"userid"`
}

func NewUserServiceGetUserInfoArgs() *UserServiceGetUserInfoArgs {
	return &UserServiceGetUserInfoArgs{}
}

func (p *UserServiceGetUserInfoArgs) InitDefault() {
}

var UserServiceGetUserInfoArgs_Userid_DEFAULT *UserID

func (p *UserServiceGetUserInfoArgs) GetUserid() (v *UserID) {
	if !p.IsSetUserid() {
		return UserServiceGetUserInfoArgs_Userid_DEFAULT
	}
	return p.Userid
}
func (p *UserServiceGetUserInfoArgs) SetUserid(val *UserID) {
	p.Userid = val
}

func (p *UserServiceGetUserInfoArgs) IsSetUserid() bool {
	return p.Userid != nil
}

func (p *UserServiceGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserInfoArgs = map[int16]string{
	1: "userid",
}

type UserServiceGetUserInfoResult struct {
	Success *UserInfo `thrift:"success,0,optional" frugal:"0,optional,UserInfo" json:"success,omitempty"`
}

func NewUserServiceGetUserInfoResult() *UserServiceGetUserInfoResult {
	return &UserServiceGetUserInfoResult{}
}

func (p *UserServiceGetUserInfoResult) InitDefault() {
}

var UserServiceGetUserInfoResult_Success_DEFAULT *UserInfo

func (p *UserServiceGetUserInfoResult) GetSuccess() (v *UserInfo) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*UserInfo)
}

func (p *UserServiceGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserInfoResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserInfoResult = map[int16]string{
	0: "success",
}
